version: '3.1'

services:

  springboot-api-demo:
    image: my_image
    ports:
      - "4005:8080"
    depends_on:
      - postgres
  postgres:
    container_name: pgdb
    image: postgres:9.6-alpine
    environment:
    - 'POSTGRES_ROOT_PASSWORD=postgres'
    - 'POSTGRES_USER=postgres'
    - 'POSTGRES_PASSWORD=1234'
    ports:
    - "5432:5432"
