version: '3.7'

services:
  springboot:
    build: .
    restart : always
    ports:
      - "4005:8080"
    depends_on:
      - postgres
  postgres:
    container_name: pgdb
    image: postgres:latest
    volumes:
      - db_pgdata:/var/lib/postgresql/data_pg
      - ./scripts/:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      - 'POSTGRES_DB=docker'
      - 'POSTGRES_ROOT_PASSWORD=postgres'
      - 'POSTGRES_USER=docker'
      - 'POSTGRES_PASSWORD=1234'
    ports:
      - "5432:5432"
volumes:
  db_pgdata: